/* eslint-disable no-unused-vars */
import { Schema, model, Model } from "mongoose";
import { TRiskAssessment } from "./riskAssessment.interface";

const YesNoFieldSchema = new Schema(
  {
    applicable: { type: Boolean },
    comments: { type: String },
    action: { type: String },
  },
  { _id: false }
);

const MovingHandlingEntrySchema = new Schema(
  {
    selectedOption: { type: String },
    score: { type: String },
    risk: { type: String },
    minimiseRisk: { type: String },
  },
  { _id: false }
);

const MedicationSchema = new Schema(
  {
    name: { type: String },
    dose: { type: String },
    frequency: { type: String },
    timeTaken: { type: String },
    numberPerDay: { type: String },
    sideEffects: { type: String },
    coshhRisk: { type: Boolean },
  },
  { _id: false }
);

const RiskAssessmentSchema = new Schema<TRiskAssessment>(
  {
    serviceUserId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Service User is required"],
    },

    // Header info
    serviceUserName: { type: String, trim: true },
    preferredTermOfAddress: { type: String },
    dateOfFirstAssessment: { type: Date },
    address: { type: String },
    dob: { type: Date },
    telNumber: { type: String },
    caseManager: { type: String },
    assessorsName: { type: String },
    assessorsSignatureUrl: { type: String },

    // Section 1: Moving & Handling
    section1Explanation: { type: String },
    mobilityEntries: [MovingHandlingEntrySchema],
    mobilityTotalScore: { type: String },
    mobilityRiskRating: { type: String },
    fallEntries: [MovingHandlingEntrySchema],
    fallTotalScore: { type: String },
    incontinenceEntries: [MovingHandlingEntrySchema],
    incontinenceTotalScore: { type: String },
    attachmentEntries: [MovingHandlingEntrySchema],
    attachmentTotalScore: { type: String },
    mentalHealthEntries: [MovingHandlingEntrySchema],
    mentalHealthTotalScore: { type: String },
    sightHearingEntries: [MovingHandlingEntrySchema],
    sightHearingTotalScore: { type: String },
    weightEntries: [MovingHandlingEntrySchema],
    weightTotalScore: { type: String },
    unpredictableMovementsEntries: [MovingHandlingEntrySchema],
    unpredictableMovementsTotalScore: { type: String },
    movingHandlingTotalScore: { type: String },
    movingHandlingRiskRating: { type: String },

    // Section 2: Moving & Handling Tasks
    section2Explanation: { type: String },
    taskEntries: [MovingHandlingEntrySchema],
    tasksTotalScore: { type: String },
    tasksRiskRating: { type: String },

    // Section 3: Medication
    section3Explanation: { type: String },
    medicationSupplies: [YesNoFieldSchema],
    takingMedication: [YesNoFieldSchema],
    topicalApplications: [YesNoFieldSchema],
    medications: [MedicationSchema],
    medicalCareTasks: [YesNoFieldSchema],
    hasAllergies: { type: Boolean },
    allergiesComments: { type: String },
    allergiesAction: { type: String },

    // Section 4: Independence Risks
    section4Explanation: { type: String },
    riskCooking: { type: Boolean },
    riskBathing: { type: Boolean },
    riskDressing: { type: Boolean },
    riskCleaning: { type: Boolean },
    riskOutings: { type: Boolean },
    riskOther: { type: Boolean },
    riskOtherText: { type: String },
    riskCookingComment: { type: String },
    riskBathingComment: { type: String },
    riskDressingComment: { type: String },
    riskCleaningComment: { type: String },
    riskOutingsComment: { type: String },
    agreedActionServiceUser: { type: String },
    workerRiskCooking: { type: Boolean },
    workerRiskBathing: { type: Boolean },
    workerRiskDressing: { type: Boolean },
    workerRiskCleaning: { type: Boolean },
    workerRiskOutings: { type: Boolean },
    workerRiskOther: { type: Boolean },
    workerRiskOtherText: { type: String },
    workerRiskCookingComment: { type: String },
    workerRiskBathingComment: { type: String },
    workerRiskDressingComment: { type: String },
    workerRiskCleaningComment: { type: String },
    workerRiskOutingsComment: { type: String },
    agreedActionWorkers: { type: String },
    aggressiveBehaviourVerbal: { type: String },
    aggressiveBehaviourVerbalAction: { type: String },
    aggressiveBehaviourPhysical: { type: String },
    aggressiveBehaviourPhysicalAction: { type: String },
    aggressiveBehaviourPhysical2: { type: String },
    aggressiveBehaviourPhysicalAction2: { type: String },
    aggressiveBehaviourPhysical3: { type: String },
    aggressiveBehaviourPhysicalAction3: { type: String },
    criminalHistory: { type: Boolean },
    criminalHistoryDetails: { type: String },
    criminalHistoryDetails2: { type: String },
    criminalHistoryDetails3: { type: String },
    criminalHistoryCarer: { type: String },
    criminalHistoryCarer2: { type: String },
    criminalHistoryCarer3: { type: String },
    transmittableDiseases: { type: String },
    transmittableDiseases2: { type: String },
    transmittableDiseases3: { type: String },
    transmittableDiseasesCarer: { type: String },
    transmittableDiseasesCarer2: { type: String },
    transmittableDiseasesCarer3: { type: String },

    // Section 5: Environment
    section5Explanation: { type: String },
    // 5A. Type of Accommodation
    accommodationType: { type: [String] },
    accommodationOther: { type: String },
    travellingRisks: { type: Boolean },
    travellingRisksDetails: { type: String },
    travellingDirectionDetails: { type: String },
    hasTelephone: { type: Boolean },
    hasTelephoneAction: { type: String },
    telephoneConcerns: { type: Boolean },
    telephoneConcernsAction: { type: String },
    highCrimeArea: { type: Boolean },
    highCrimeAreaAction: { type: String },
    areaIsolated: { type: Boolean },
    areaIsolatedAction: { type: String },
    safetyRisksComments: { type: String },
    waterCutOff: { type: String },
    gasCutOff: { type: String },
    electricMeter: { type: String },
    electricalWiringConcerns: { type: Boolean },
    electricMeterType: { type: String },
    lightingConcerns: { type: Boolean },
    circuitBreaker: { type: Boolean },
    residualCurrentDevice: { type: Boolean },
    heatingSource: { type: String },
    gasConcerns: { type: Boolean },
    heatingConcerns: { type: Boolean },
    cookingSource: { type: String },
    hotWaterConcerns: { type: Boolean },
    thermostaticRegulator: { type: Boolean },
    securityLocks: { type: Boolean },
    keyBox: { type: Boolean },
    keyBoxLocation: { type: String },
    stairGates: { type: Boolean },
    monitoredMedicationBox: { type: Boolean },
    keySafe: { type: Boolean },
    serviceUserSmoker: { type: Boolean },
    fireHazards: { type: Boolean },
    staffRisks: { type: Boolean },
    serviceUserRisks: { type: Boolean },
    fireOfficerAssessment: { type: Boolean },
    fireEscapeRoutes: { type: String },
    unauthorisedActivitiesClarified: { type: Boolean },
    adequateLighting: { type: Boolean },
    accessWaysHazards: { type: Boolean },
    buildingRepair: { type: Boolean },
    tripsFallsHazards: { type: Boolean },
    stairsRepair: { type: Boolean },
    lowCeilings: { type: Boolean },
    ventilationConcerns: { type: Boolean },
    leadConcerns: { type: Boolean },
    asbestosConcerns: { type: Boolean },
    noiseConcerns: { type: Boolean },
    dirtDustConcerns: { type: Boolean },
    wasteConcerns: { type: Boolean },
    pestInfestation: { type: Boolean },
    unsanitaryConditions: { type: Boolean },
    coldHeatConcerns: { type: Boolean },
    roomSizeConcerns: { type: Boolean },
    liftsHoistsConcerns: { type: Boolean },
    adaptationsConcerns: { type: Boolean },
    brokenGlazing: { type: Boolean },
    coshhSubstances: { type: Boolean },
    coshhRequiredSubstances: { type: Boolean },
    coshhSheetsAvailable: { type: Boolean },
    animalsInHome: { type: Boolean },
    animalSafetyRisk: { type: Boolean },
    animalHygieneRisk: { type: Boolean },
    animalWaste: { type: Boolean },
    environmentalWaste: { type: Boolean },
    bodilyExcrements: { type: Boolean },
    identifiedRisksStaff: { type: Boolean },
    crackedWindows: { type: Boolean },
    crackedWindowsDoNotClean: { type: Boolean },
    identifiedRisksServiceUser: { type: Boolean },
    protectiveClothingNeeded: { type: Boolean },
    risksToStaff: { type: Boolean },
    risksToServiceUser: { type: Boolean },
    risksToOthers: { type: Boolean },
    cashSecure: { type: Boolean },
    financialRisks: { type: Boolean },
    financialRisksMinimise: { type: String },
    staffHandleMoney: { type: Boolean },
    foodInDate: { type: Boolean },
    foodPreparation: { type: Boolean },
    foodHygieneStandards: { type: Boolean },
    cookingFacilitiesSafe: { type: Boolean },
    refrigeratorTemp: { type: Boolean },
    freezerTemp: { type: Boolean },
    handWashingFacilities: { type: Boolean },
    kitchenClean: { type: Boolean },
    separateStorage: { type: Boolean },
    hotColdWater: { type: Boolean },
    staffTrainingNeeded: { type: Boolean },
    outingStaffRisks: { type: Boolean },
    outingServiceUserRisks: { type: Boolean },
    staffTakeOut: { type: Boolean },
    staffTransport: { type: Boolean },
    publicTransport: { type: Boolean },
    otherTransport: { type: Boolean },
    carUsed: { type: Boolean },

    // Section 6: Support Staff Input
    section6Explanation: { type: String },
    careWorkerComments: { type: String },
    additionalRisksIdentified: { type: String },

    // Section 7: Action Plan
    actionNeededPriorService: { type: String },
    assessorName: { type: String },
    assessorSignatureUrl: { type: String },
    assessorDate: { type: Date },
    serviceUserNameKin: { type: String },
    serviceUserSignatureUrl: { type: String },
    serviceUserDate: { type: Date },
    nextReviewDate: { type: Date },
    personResponsible: { type: String },
    dateCompletionReview: { type: Date },
    equipmentRequired: { type: String },
    equipmentSupplierName: { type: String },
    equipmentSupplierTel: { type: String },
    equipmentServiceInterval: { type: String },
    equipmentServiceDate: { type: Date },
    hoistServiceDate: { type: Date },

    // Details (free text) for environment / premises / finance / food / outings checks
    electricalWiringConcernsDetails: { type: String },
    circuitBreakerDetails: { type: String },
    residualCurrentDeviceDetails: { type: String },
    lightingConcernsDetails: { type: String },
    gasConcernsDetails: { type: String },
    heatingConcernsDetails: { type: String },
    hotWaterConcernsDetails: { type: String },
    thermostaticRegulatorDetails: { type: String },
    securityLocksDetails: { type: String },
    stairGatesDetails: { type: String },
    monitoredMedicationBoxDetails: { type: String },
    keySafeDetails: { type: String },
    serviceUserSmokerDetails: { type: String },
    fireHazardsDetails: { type: String },
    staffRisksDetails: { type: String },
    serviceUserRisksDetails: { type: String },
    fireOfficerAssessmentDetails: { type: String },
    unauthorisedActivitiesClarifiedDetails: { type: String },
    adequateLightingDetails: { type: String },
    accessWaysHazardsDetails: { type: String },
    buildingRepairDetails: { type: String },
    tripsFallsHazardsDetails: { type: String },
    stairsRepairDetails: { type: String },
    lowCeilingsDetails: { type: String },
    ventilationConcernsDetails: { type: String },
    leadConcernsDetails: { type: String },
    asbestosConcernsDetails: { type: String },
    noiseConcernsDetails: { type: String },
    dirtDustConcernsDetails: { type: String },
    wasteConcernsDetails: { type: String },
    pestInfestationDetails: { type: String },
    unsanitaryConditionsDetails: { type: String },
    coldHeatConcernsDetails: { type: String },
    roomSizeConcernsDetails: { type: String },
    liftsHoistsConcernsDetails: { type: String },
    adaptationsConcernsDetails: { type: String },
    brokenGlazingDetails: { type: String },
    coshhSubstancesDetails: { type: String },
    coshhRequiredSubstancesDetails: { type: String },
    coshhSheetsAvailableDetails: { type: String },
    animalsInHomeDetails: { type: String },
    animalSafetyRiskDetails: { type: String },
    animalHygieneRiskDetails: { type: String },
    animalWasteDetails: { type: String },
    environmentalWasteDetails: { type: String },
    bodilyExcrementsDetails: { type: String },
    identifiedRisksStaffDetails: { type: String },
    crackedWindowsDetails: { type: String },
    crackedWindowsDoNotCleanDetails: { type: String },
    identifiedRisksServiceUserDetails: { type: String },
    protectiveClothingNeededDetails: { type: String },
    risksToStaffDetails: { type: String },
    risksToServiceUserDetails: { type: String },
    risksToOthersDetails: { type: String },
    cashSecureDetails: { type: String },
    staffHandleMoneyDetails: { type: String },
    foodInDateDetails: { type: String },
    foodPreparationDetails: { type: String },
    foodHygieneStandardsDetails: { type: String },
    cookingFacilitiesSafeDetails: { type: String },
    refrigeratorTempDetails: { type: String },
    freezerTempDetails: { type: String },
    handWashingFacilitiesDetails: { type: String },
    kitchenCleanDetails: { type: String },
    separateStorageDetails: { type: String },
    hotColdWaterDetails: { type: String },
    staffTrainingNeededDetails: { type: String },
    outingStaffRisksDetails: { type: String },
    outingServiceUserRisksDetails: { type: String },
    staffTakeOutDetails: { type: String },
    staffTransportDetails: { type: String },
    publicTransportDetails: { type: String },
    otherTransportDetails: { type: String },
    carUsedDetails: { type: String },
  },
  {
    timestamps: true,
  }
);

export const RiskAssessment: Model<TRiskAssessment> = model<TRiskAssessment>(
  "RiskAssessment",
  RiskAssessmentSchema
);
